### ISSUE TITLE
Please tell me the license

### ISSUE THREAD

**Issue by ES0729dhun** [suer/redmine_export_with_journals#6]
Please tell me the license of this plug-in.

If there is no license, please tell me the following information：
1. Is this plug-in free?
2. Can I use this plug-in for commercial?

**Comment by suer** [comment]
You can use this plugin under MIT license.(I will add license file in this repository.)

So, 
1. This plug-in is free.
2. You can use this plug-in for commercial.

**Comment by ES0729dhun** [comment]
Thank you very much.
