### ISSUE TITLE
説明出てこないです

### ISSUE THREAD

**Issue by EricAveritt** [suer/redmine_export_with_journals#7]
すべての項目と説明のチェックボックスを選択したら説明がCSVにありません。

使ってるRedmineはBitnamiの3.4.6-3です。

**Comment by suer** [comment]
どこかのバージョンでパラメータが変わっていたようです。
099dc3d4658d104b549b5952aa43ba4996b52c53 で修正しました。
ただし Redmine 4.0 以降の対応となります。
